### ISSUE TITLE
licq crashes when connecting to jabber server

### ISSUE THREAD

**Issue by reald** [licq-im/licq#48]
Steps to reproduce with licq 1.8.2 (on Ubuntu 16.04 LTS):
1. Connect to jabber server
2. licq crashes

cat /home/foo/.licq/licq.backtrace

```
time: 1463497724
licq() [0x481e1d]
/lib/x86_64-linux-gnu/libc.so.6(+0x354a0) [0x7f7c9fab84a0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7f7c9fab8418]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f7c9faba01a]
licq() [0x481942]
/lib/x86_64-linux-gnu/libc.so.6(+0x354a0) [0x7f7c9fab84a0]
/usr/lib/x86_64-linux-gnu/libgnutls.so.30(+0x946ed) [0x7f7c9b0956ed]
/usr/lib/x86_64-linux-gnu/libgnutls.so.30(+0x960b8) [0x7f7c9b0970b8]
/usr/lib/x86_64-linux-gnu/libgnutls.so.30(gnutls_x509_crt_verify+0x2d) [0x7f7c9b09772d]
/usr/lib/x86_64-linux-gnu/libgloox.so.13(_ZN5gloox12GnuTLSClient16verifyAgainstCAsEP19gnutls_x509_crt_intPS2_i+0x2c) [0x7f7c9b836a7c]
/usr/lib/x86_64-linux-gnu/libgloox.so.13(_ZN5gloox12GnuTLSClient11getCertInfoEv+0x140) [0x7f7c9b836bf0]
/usr/lib/x86_64-linux-gnu/libgloox.so.13(_ZN5gloox10GnuTLSBase9handshakeEv+0x6d) [0x7f7c9b8392bd]
/usr/lib/x86_64-linux-gnu/libgloox.so.13(_ZN5gloox10GnuTLSBase7decryptERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xf1) [0x7f7c9b839111]
/usr/lib/x86_64-linux-gnu/libgloox.so.13(_ZN5gloox19ConnectionTCPClient4recvEi+0xfc) [0x7f7c9b7d135c]
licq(_ZN4Licq8MainLoop3runEv+0x2f8) [0x4750b8]
/usr/lib/licq/protocol_jabber.so(+0x10b8d) [0x7f7c9bac3b8d]
licq(_ZN10LicqDaemon14PluginInstance16startThreadEntryEPv+0x58) [0x4d9c98]
licq() [0x4db406]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76fa) [0x7f7ca11e96fa]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f7c9fb89b5d]

```

cat /home/foo/.licq/licq.backtrace.gdb 

```
Thread 3 (Thread 0x7f7c9c4d0700 (LWP 3419)):
#0  0x00007f7ca11f2fbb in __waitpid (pid=3462, stat_loc=0x7f7c9c4ce23c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x0000000000481cdb in ?? ()
#2  <signal handler called>
#3  0x00007f7c9fab8418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#4  0x00007f7c9faba01a in __GI_abort () at abort.c:89
#5  0x0000000000481942 in ?? ()
#6  <signal handler called>
#7  0x00007f7c9b0956ed in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#8  0x00007f7c9b0970b8 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#9  0x00007f7c9b09772d in gnutls_x509_crt_verify () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#10 0x00007f7c9b836a7c in gloox::GnuTLSClient::verifyAgainstCAs(gnutls_x509_crt_int*, gnutls_x509_crt_int**, int) () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
#11 0x00007f7c9b836bf0 in gloox::GnuTLSClient::getCertInfo() () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
#12 0x00007f7c9b8392bd in gloox::GnuTLSBase::handshake() () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
#13 0x00007f7c9b839111 in gloox::GnuTLSBase::decrypt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
#14 0x00007f7c9b7d135c in gloox::ConnectionTCPClient::recv(int) () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
#15 0x00000000004750b8 in Licq::MainLoop::run() ()
#16 0x00007f7c9bac3b8d in ?? () from /usr/lib/licq/protocol_jabber.so
#17 0x00000000004d9c98 in LicqDaemon::PluginInstance::startThreadEntry(void*) ()
#18 0x00000000004db406 in ?? ()
#19 0x00007f7ca11e96fa in start_thread (arg=0x7f7c9c4d0700) at pthread_create.c:333
#20 0x00007f7c9fb89b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f7c9a07d700 (LWP 3420)):
#0  0x00007f7c9fb7de8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000000474f0a in Licq::MainLoop::run() ()
#2  0x00007f7c99676e2c in ?? () from /usr/lib/licq/licq_rms.so
#3  0x00000000004d9c98 in LicqDaemon::PluginInstance::startThreadEntry(void*) ()
#4  0x00000000004db406 in ?? ()
#5  0x00007f7ca11e96fa in start_thread (arg=0x7f7c9a07d700) at pthread_create.c:333
#6  0x00007f7c9fb89b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f7ca15e1740 (LWP 3418)):
#0  0x00007f7c9fb7de8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000000474f0a in Licq::MainLoop::run() ()
#2  0x000000000046355d in CLicq::Main() ()
#3  0x00000000004505a9 in main ()

Thread 3 (Thread 0x7f7c9c4d0700 (LWP 3419)):
#0  0x00007f7ca11f2fbb in __waitpid (pid=3462, stat_loc=0x7f7c9c4ce23c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
#1  0x0000000000481cdb in ?? ()
No symbol table info available.
#2  <signal handler called>
No locals.
#3  0x00007f7c9fab8418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 3418
        selftid = 3419
#4  0x00007f7c9faba01a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x81, sa_sigaction = 0x81}, sa_mask = {__val = {140173235222816, 140173036257040, 140173260047242, 18446744073709551615, 39, 25554864, 562945658454021, 38, 140173232282157, 140173235226480, 38, 140173174950448, 140173174966016, 38, 212, 140173174962836}}, sa_flags = -1672676712, sa_restorer = 0xd4}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#5  0x0000000000481942 in ?? ()
No symbol table info available.
#6  <signal handler called>
No locals.
#7  0x00007f7c9b0956ed in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
No symbol table info available.
#8  0x00007f7c9b0970b8 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
No symbol table info available.
#9  0x00007f7c9b09772d in gnutls_x509_crt_verify () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
No symbol table info available.
#10 0x00007f7c9b836a7c in gloox::GnuTLSClient::verifyAgainstCAs(gnutls_x509_crt_int*, gnutls_x509_crt_int**, int) () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
No symbol table info available.
#11 0x00007f7c9b836bf0 in gloox::GnuTLSClient::getCertInfo() () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
No symbol table info available.
#12 0x00007f7c9b8392bd in gloox::GnuTLSBase::handshake() () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
No symbol table info available.
#13 0x00007f7c9b839111 in gloox::GnuTLSBase::decrypt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
No symbol table info available.
#14 0x00007f7c9b7d135c in gloox::ConnectionTCPClient::recv(int) () from /usr/lib/x86_64-linux-gnu/libgloox.so.13
No symbol table info available.
#15 0x00000000004750b8 in Licq::MainLoop::run() ()
No symbol table info available.
#16 0x00007f7c9bac3b8d in ?? () from /usr/lib/licq/protocol_jabber.so
No symbol table info available.
#17 0x00000000004d9c98 in LicqDaemon::PluginInstance::startThreadEntry(void*) ()
No symbol table info available.
#18 0x00000000004db406 in ?? ()
No symbol table info available.
#19 0x00007f7ca11e96fa in start_thread (arg=0x7f7c9c4d0700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f7c9c4d0700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140173174966016, -2635496963366970879, 0, 140732342552015, 140173174966720, 140732342552704, 2708332298698496513, 2708237071505299969}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#20 0x00007f7c9fb89b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 2 (Thread 0x7f7c9a07d700 (LWP 3420)):
#0  0x00007f7c9fb7de8d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x0000000000474f0a in Licq::MainLoop::run() ()
No symbol table info available.
#2  0x00007f7c99676e2c in ?? () from /usr/lib/licq/licq_rms.so
No symbol table info available.
#3  0x00000000004d9c98 in LicqDaemon::PluginInstance::startThreadEntry(void*) ()
No symbol table info available.
#4  0x00000000004db406 in ?? ()
No symbol table info available.
#5  0x00007f7ca11e96fa in start_thread (arg=0x7f7c9a07d700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f7c9a07d700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140173136877312, -2635496963366970879, 0, 140732342551983, 140173136878016, 1, 2708318648755558913, 2708237071505299969}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007f7c9fb89b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 1 (Thread 0x7f7ca15e1740 (LWP 3418)):
#0  0x00007f7c9fb7de8d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x0000000000474f0a in Licq::MainLoop::run() ()
No symbol table info available.
#2  0x000000000046355d in CLicq::Main() ()
No symbol table info available.
#3  0x00000000004505a9 in main ()
No symbol table info available.

time: 1463497724
```

**Comment by erijo** [comment]
Hi,
Thanks for your report. I'm sorry to inform you that Licq development has stopped so this issue will most likely not be dealt with.
